package constant

/**
服务器相关
 */
const (
	SERVER_PROTOCOL = "tcp"
	SERVER_ADDR     = "127.0.0.1"
	SERVER_PORT     = "8088"
	SERVER_CLOSE    = "close"
)

/**
登录相关
 */
const (
	//连接
	CALL_COMMON_CONNECTION = "CALL_COMMON_CONNECTION"
	//关闭连接
	CALL_COMMON_CLOSE   = "CALL_COMMON_CLOSE"
)

/**
会话相关
 */
const (
	CALL_TYPE_BROADCAST = "CALL_TYPE_BROADCAST"
	CALL_TYPE_GROUP     = "CALL_TYPE_GROUP"
	CALL_TYPE_P2P       = "CALL_TYPE_P2P"
	CALL_TYPE_COMMOND   = "CALL_TYPE_COMMOND"
)

const (
	CALL_GROUP_DEFAULT = "DEFAULT_GROUP"
)

